url: https://prabuddha.me
bio: >
  Container enthusiast. Software Engineer & Solution Architect focusing on building highly scalable services.

layout: stacked
style: light

post:
  layout: sidebar

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
   medium: prabch
   linkedin: prabch
   stackoverflow: 4293543/prabuddha-chakraborty

theme: jekyll-theme-minimal
