url: https://prabuddha.me
bio: >
  Saving tech stuff, just for the record.
  Say hello at mail@prabuddha.me

layout: stacked #sidebar
style: light

post:
  layout: sidebar

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
   facebook: prabuddha.nike13
   linkedin: prabuddha90
   stackoverflow: 4293543/prabuddha-chakraborty
   twitter: _iam404
   website: https://prabuddha.me

#topics:
#  - name: CSS
#    web_url: https://github.com/topics/css
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png#
#
#  - name: Web design
#
#  - name: Sass
#    web_url: https://github.com/topics/sass
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

theme: jekyll-theme-minimal